#!/bin/bash

#####################################################################################
# common
IP=172.17.77.4
MASK=24
GATEWAY=172.17.42.1
VERSION=

# create user/pass && db
DB_NAME=redmine_production,gitlab_ci_production,archiva_production
DB_USER=mysql
DB_PASS=mysql

# data
VOLUME_DATA=$HOME/appstore/tfs/mysql/data
#####################################################################################

VERSION=${VERSION:-"latest"};
if [ $# -lt 1 ]; then
    echo "Usage: tfs-mysql run|start|stop|clean";
    exit 0;
fi

# 启动
function start_docker {
    sudo docker start tfs-mysql;
    sudo pipework docker0 tfs-myql $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}

# 停止容器
function stop_docker {
    sudo docker stop tfs-mysql;
}

# 创建并初始化+启动容器
function run_docker {
    echo "run docker using image[hary/mysql] version[$VERSION]";
    sudo docker run -i -t -d --hostname=tfs-mysql --name=tfs-mysql \
    -e "DB_NAME=$DB_NAME" \
    -e "DB_USER=$DB_USER" \
    -e "DB_PASS=$DB_PASS" \
    -v $VOLUME_DATA:/var/lib/mysql \
    hary/mysql:$VERSION;

    # IP地址设置
    sudo pipework docker0 tfs-mysql $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}


#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   # clean volume data
   clean) sudo rm -fr $VOLUME_DATA/*;;
esac 


